[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap_program = "AjR1S8tTbCkiw18urVfP8GErdLYYpQVQfX815AACP5rj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mayank/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
